### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Screwtapello** [byuu/higan#11] opened 2019-07-25 18:20 UTC
higan v108 is very different from earlier versions, and the documentation will need a lot of updating.

As well as actually writing the docs, we will also need:

- [ ] `mkdocs.yml` to be replaced
- [ ] Add the `mkdocs` package back to the CI build scripts
- [ ] Add the documentation-building command sback to the CI build scripts:

      LC_ALL=C.UTF-8 mkdocs build
      cp -a docs_build higan-nightly/docs

**Comment by byuu** [comment] 2019-07-25 18:40
Difficult part will be where to stop making changes and where to start writing documentation.

I really feel we need a round of public testing of the new higan GUI, get some feedback, make changes, maybe repeat a few times. Maybe we need some micro-documentation to help get that process started.

I've been over here slowly revising the higan GUI to be functional. Got light gun support and mouse/joypad mapping in the other day, still need rumble support re-added.

The template system and the default folder locations for games are the obvious sore points right now. The, er, fragility of the settings.bml files is another serious problem.

The extra abstraction layer involved with higan::Node has really made writing and maintaining this code extremely difficult =(

**Comment by Screwtapello** [comment] 2019-07-26 09:09
As I mentioned in #4, I imagine (hope) that writing documentation will help highlight which parts of the GUI have the sharpest edges. If I write documentation, and then the GUI changes and I have to rewrite documentation, I'll feel like I've done good work. You know, a bit like Caroline Rose in [the Inside Macintosh story](http://www.folklore.org/StoryView.py?project=Macintosh&story=Inside_Macintosh.txt).

Once we get to the point where we can point people toward a download that they can extract and run immediately (even if it's buggy or awkward when running), I can write some docs that let people get started.

**Comment by Screwtapello** [comment] 2019-10-09 11:09
For completeness, I wrote up [a very simple getting started guide](https://zork.net/~st/jottings/Getting_Started_with_higan_v106.217.html).

#47 checks off the first item in the OP, at least.

**Comment by russellballestrini** [comment] 2019-12-29 13:42
I am missing the controller templates on my nightly binaries download, I'm going to try your guide and let you know how it works for me. (Linux Fedora)

**Comment by allanin** [comment] 2020-01-01 07:22
I can confirm this bug using Windows. Higan was also started with admin rights to ensure there is no rights problems.

**Comment by Screwtapello** [comment] 2020-01-01 08:07
The "no controller templates" thing is very likely issue #4.

**Comment by byuu** [comment] 2020-02-29 11:53
Apologies, but I don't want to maintain the documentation inside GitHub, so I'm going to close this out. I would like to get new documentation written, but I feel it should be on byuu.org instead. Maybe when I have some free time I can work on that ... for now, there's https://byuu.org/higan/user-guide at least ...

**Closed by byuu** 2020-02-29 11:53 UTC
